CREATE TABLE products (
    product_id      NUMBER(6) PRIMARY KEY,
    product_name    VARCHAR2(100) NOT NULL,
    unit_cost       NUMBER(10, 2) NOT NULL,
    reorder_point   NUMBER(5) NOT NULL,
    -- Constraint to ensure reorder point is positive
    CONSTRAINT chk_reorder_point CHECK (reorder_point > 0)
);

INSERT INTO products (product_id, product_name, unit_cost, reorder_point) VALUES (4001, 'Motor Oil', 25.00, 50);
INSERT INTO products (product_id, product_name, unit_cost, reorder_point) VALUES (4002, 'Deluxe Gear Set', 50.00, 50);
INSERT INTO products (product_id, product_name, unit_cost, reorder_point) VALUES (4003, 'Critical Gasket Pack', 100.00, 10);
INSERT INTO products (product_id, product_name, unit_cost, reorder_point) VALUES (4004, 'Bulk Connector', 10.00, 50);
COMMIT;


CREATE TABLE inventory_stock (
    stock_id        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    product_id      NUMBER(6) NOT NULL,
    warehouse_id    NUMBER(2) NOT NULL,
    stock_level     NUMBER(5) NOT NULL,
    last_checked    DATE DEFAULT SYSDATE,
    CONSTRAINT fk_product_stock FOREIGN KEY (product_id) REFERENCES products(product_id),
    CONSTRAINT chk_stock_level CHECK (stock_level >= 0)
);

INSERT INTO inventory_stock (product_id, warehouse_id, stock_level) VALUES (4001, 10, 150);
INSERT INTO inventory_stock (product_id, warehouse_id, stock_level) VALUES (4002, 10, 35);
INSERT INTO inventory_stock (product_id, warehouse_id, stock_level) VALUES (4003, 11, 5); 
INSERT INTO inventory_stock (product_id, warehouse_id, stock_level) VALUES (4004, 11, 200);
COMMIT;

CREATE TABLE audit_log (
    log_id          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    log_timestamp   TIMESTAMP DEFAULT SYSTIMESTAMP,
    process_name    VARCHAR2(50) NOT NULL,
    product_id      NUMBER(6),
    log_message     VARCHAR2(500)
);


SELECT
    product_id,
    product_name,
    unit_cost,
    reorder_point
FROM
    products
ORDER BY
    product_id;


SELECT
    s.stock_id,
    s.warehouse_id,
    p.product_name,
    s.stock_level
FROM
    inventory_stock s
JOIN
    products p ON s.product_id = p.product_id
ORDER BY
    s.product_id;
